Document: libsigrok4dslogic
Title: Debian libsigrok4dslogic Manual
Author: <insert document author here>
Abstract: This manual describes what libsigrok4dslogic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsigrok4dslogic/libsigrok4dslogic.sgml.gz

Format: postscript
Files: /usr/share/doc/libsigrok4dslogic/libsigrok4dslogic.ps.gz

Format: text
Files: /usr/share/doc/libsigrok4dslogic/libsigrok4dslogic.text.gz

Format: HTML
Index: /usr/share/doc/libsigrok4dslogic/html/index.html
Files: /usr/share/doc/libsigrok4dslogic/html/*.html
